### ISSUE TITLE
Internal server error previewing large zip

### ISSUE THREAD

**Issue by SamuelBradley** [AuScope/ckan-docker#139]
Uploaded a large zip file ~350MB, went to preview the file after upload and got the following error.

![image](https://github.com/AuScope/ckan-docker/assets/3054530/4f291101-f7e9-4589-b782-4408c0913800)

![image](https://github.com/AuScope/ckan-docker/assets/3054530/65629899-8af2-490c-be36-f4426f74a575)

**Comment by stuartwoodman** [comment]
Suspect a resource issue but will know more after I look at some logs.

**Comment by stuartwoodman** [comment]
Something bigger going wrong, investigating:

2024-05-20 00:00:23,957 ERROR [ckan.config.middleware.flask_app] 'S3ResourceUploader' object has no attribute 'get_url_from_filename'
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/srv/app/src/ckan/ckan/config/middleware/../../views/resource.py", line 618, in view
    return h.rendered_resource_view(view, resource, package, embed=True)
  File "/srv/app/src/ckan/ckan/lib/helpers.py", line 2269, in rendered_resource_view
    return literal(base.render(template, extra_vars=data_dict))
  File "/srv/app/src/ckan/ckan/lib/base.py", line 107, in render
    return flask_render_template(template_name, **extra_vars)
  File "/usr/lib/python3.10/site-packages/flask/templating.py", line 147, in render_template
    return _render(
  File "/usr/lib/python3.10/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/usr/lib/python3.10/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/srv/app/src/ckanext-zippreview/ckanext/zippreview/templates/zip.html", line 1, in top-level template code
    {% extends 'dataviewer/base.html' %}
  File "/srv/app/src/ckan/ckan/templates/dataviewer/base.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/usr/lib/python3.10/site-packages/ckanext/auscope_theme/templates/base.html", line 1, in top-level template code
    {% ckan_extends %}
  File "/srv/app/src/ckanext-scheming/ckanext/scheming/templates/base.html", line 1, in top-level template code
    {% ckan_extends %}
  File "/srv/app/src/ckan/ckan/templates/base.html", line 108, in top-level template code
    {%- block page %}{% endblock -%}
  File "/srv/app/src/ckanext-zippreview/ckanext/zippreview/templates/zip.html", line 11, in block 'page'
    {% set tree = h.get_zip_tree(resource) %}
  File "/srv/app/src/ckanext-zippreview/ckanext/zippreview/utils.py", line 103, in get_zip_tree
    zip_list = get_zip_list(rsc)
  File "/srv/app/src/ckanext-zippreview/ckanext/zippreview/utils.py", line 38, in get_zip_list
    URL = upload.get_url_from_filename(rsc['id'], filename, '')
AttributeError: 'S3ResourceUploader' object has no attribute 'get_url_from_filename'

**Comment by stuartwoodman** [comment]
Yep, zippreview doesn't seem to play nice with s3filestore.
Options are to fork or copy zippreview to our ckan-docker distribution and make changes to it, or switch to the alternative cloudstorage plugin. I might investigate the first option, see of there isn't a quick hack we can put in.

**Comment by stuartwoodman** [comment]
I created a forked version of ckanext-zippreview that solves this:
https://github.com/AuScope/ckanext-zippreview/tree/master

Pull request for this:
https://github.com/AuScope/ckan-docker/pull/193

**Comment by SamuelBradley** [comment]
@stuartwoodman After merging in the PR I am still getting the error in Dev with both large (> 300MB) and Small (< 30MB) Zip files I will double check that the new image deployed correctly

**Comment by stuartwoodman** [comment]
@SamuelBradley Looks like it deployed properly, I inspected the zip-preview code in the deployed extensions directory and it's now using our fork. I think this will be a tough one to debug as there aren't any errors in dev's log. So the code is doing its job insofar as it seems to be detecting the S3ResourceUploader correctly and calling the new method, but then..? If the actual file retrieval were to fail I'd expect an error.

Not sure how to approach this one at this stage. May need a new zip-preview branch with more log messages, or just hack master with the same and redeploy to get some idea of what's happening.

**Comment by kitchenprinzessin3880** [comment]
@stuartwoodman is this done?
i can view the zip file contents e.g. 
<img width="1044" alt="Screenshot 2024-06-12 at 11 29 45 AM" src="https://github.com/AuScope/ckan-docker/assets/11935313/28c54815-9594-4112-ba7b-f924a21ed078">
